version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cpo-app
    restart: always
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "postgresql://cpo_admin:amu_cpo@172.17.0.1:5432/amu_cpo_db"
      NEXTAUTH_URL: "http://10.0.93.69:3000"
      AUTH_TRUST_HOST: "true"
      NEXTAUTH_SECRET: "amu-cpo-prod-secret"
      AUTH_SECRET: "amu-cpo-prod-secret"
      
      SMTP_HOST: "smtp.gmail.com"
      SMTP_PORT: "587"
      SMTP_USER: "${SMTP_USER:-}"
      SMTP_PASS: "${SMTP_PASS:-}"
      SMTP_FROM: "${SMTP_FROM:-CPO AMU <noreply@amu.ac.in>}"
      NEXT_PUBLIC_APP_NAME: "AMU CPO Procurement Portal"
    volumes:
      - cpo_uploads:/app/public/uploads

volumes:
  cpo_uploads: